/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 lifepathbook.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Model({ animValues, ...props }: any) {
  const { nodes, materials } = useGLTF("/models/lifepathbook.glb") as any;
  const rightFoldRef = React.useRef<any>(null);
  const leftFoldRef = React.useRef<any>(null);

  useFrame(() => {
    if (rightFoldRef.current && leftFoldRef.current && animValues.current) {
      // Apply the 'open' value to the folds
      rightFoldRef.current.rotation.x = -animValues.current.open;
      leftFoldRef.current.rotation.x = animValues.current.open;
    }
  });
  return (
    <group scale={0.6} {...props} dispose={null}>
      <group
        ref={rightFoldRef}
        position={[-8.835, -21.475, -0.431]}
        // position={[-7.935, 3.073, -0.435]}
        // rotation={[-Math.PI / 2, 0, 0]}
        // rotation={[-Math.PI / 2.5, 0, 0]}
      >
        <mesh geometry={nodes.book_a_0.geometry} material={materials.book_a} />
        <mesh
          geometry={nodes.book_a_0_1.geometry}
          material={materials["WhatsApp Image 2026-02-04 at 4.37.57 PM"]}
        />
      </group>
      <group
        ref={leftFoldRef}
        position={[-8.835, -21.475, -0.431]}
        // position={[-7.935, 3.073, -0.435]}
        // rotation={[-1.581, 0, 0]}
        // rotation={[-Math.PI / 2.5, 0, 0]}
      >
        <mesh
          geometry={nodes.book_a_0001.geometry}
          material={materials.book_a}
        />
        <mesh
          geometry={nodes.book_a_0001_1.geometry}
          material={materials["Material.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/lifepathbook.glb");
