export type JobRegion = "nepal" | "global";

export type Job = {
  id: number;
  title: string;
  company: string;
  location: string;
  region: JobRegion;
  type: string;
  salary: string;
  experience: string;
  category: string;
  postedDate: string;
  img: string;
  summary: string;
  responsibilities: string[];
  requirements: string[];
};

export const jobs: Job[] = [
  {
    id: 1,
    title: "Web Developer Junior",
    company: "WebX Nepal Pvt. Ltd.",
    location: "Kathmandu, Nepal",
    region: "nepal",
    type: "Full time",
    salary: "18k, 20K, 25K",
    experience: "1-4 yrs exp",
    category: "Web Developer",
    postedDate: "1 hour ago",
    img: "/company-logo/webx.png",
    summary:
      "Build and maintain production web apps, collaborate with cross-functional teams, and deliver high-quality features.",
    responsibilities: [
      "Develop and ship new product features using React and TypeScript",
      "Write clean, testable, and maintainable code",
      "Collaborate with design and QA teams on implementation",
      "Fix bugs and improve existing systems",
      "Participate in code reviews and learn best practices",
    ],
    requirements: [
      "Solid understanding of JavaScript/TypeScript",
      "Experience with React or Vue.js",
      "Familiar with REST APIs and HTTP",
      "Problem-solving mindset",
      "Git version control knowledge",
    ],
  },
  {
    id: 2,
    title: "Web Developer Senior",
    company: "WebX Nepal Pvt. Ltd.",
    location: "Kathmandu, Nepal",
    region: "nepal",
    type: "Full time",
    salary: "73k, 75K, 85K",
    experience: "5-7 yrs exp",
    category: "Web Developer",
    postedDate: "1 hour ago",
    img: "/company-logo/webx.png",
    summary:
      "Lead web development initiatives, mentor junior developers, and architect scalable solutions.",
    responsibilities: [
      "Design and implement scalable web applications",
      "Mentor and guide junior developers",
      "Conduct code reviews and establish best practices",
      "Optimize application performance and security",
      "Lead technical discussions and architecture decisions",
    ],
    requirements: [
      "Expert-level JavaScript/TypeScript knowledge",
      "5+ years with React, Vue, or Angular",
      "Experience with microservices and APIs",
      "Strong system design skills",
      "Leadership and mentoring experience",
    ],
  },
  {
    id: 3,
    title: "Full Stack Developer",
    company: "TechVision UAE",
    location: "Dubai, UAE",
    region: "global",
    type: "Full time",
    salary: "80k-120k",
    experience: "4-8 yrs exp",
    category: "Full Stack",
    postedDate: "2 hours ago",
    img: "/company-logo/cursor.svg",
    summary:
      "Build end-to-end web applications with modern front-end and back-end technologies for enterprise clients.",
    responsibilities: [
      "Develop REST APIs and GraphQL services using Node.js",
      "Build responsive React/Vue front-end applications",
      "Design and optimize database schemas (PostgreSQL, MongoDB)",
      "Deploy and monitor applications on AWS/Azure",
      "Lead architecture decisions and technical mentoring",
    ],
    requirements: [
      "4+ years with React/Vue and Node.js",
      "Database expertise (SQL and NoSQL)",
      "Cloud platform experience (AWS/Azure/GCP)",
      "Docker and Kubernetes knowledge",
      "Strong architectural thinking",
    ],
  },
  {
    id: 4,
    title: "Frontend Developer",
    company: "Innovation Labs Australia",
    location: "Sydney, Australia",
    region: "global",
    type: "Full time",
    salary: "90k-130k AUD",
    experience: "3-6 yrs exp",
    category: "Frontend Developer",
    postedDate: "3 hours ago",
    img: "/company-logo/cursor.svg",
    summary:
      "Create stunning, responsive user interfaces using modern frameworks and design systems.",
    responsibilities: [
      "Build reusable UI components and design systems",
      "Implement responsive designs across all devices",
      "Optimize front-end performance and accessibility",
      "Collaborate with designers on UX implementation",
      "Maintain component documentation and Storybook",
    ],
    requirements: [
      "Expert React or Vue.js skills",
      "Strong CSS and responsive design knowledge",
      "Experience with component libraries",
      "Testing frameworks (Jest, React Testing Library)",
      "Figma collaboration experience",
    ],
  },
  {
    id: 5,
    title: "Backend Developer",
    company: "CloudScale USA",
    location: "San Francisco, USA",
    region: "global",
    type: "Full time",
    salary: "120k-180k",
    experience: "4-7 yrs exp",
    category: "Backend Developer",
    postedDate: "4 hours ago",
    img: "/company-logo/cursor.svg",
    summary:
      "Design and build scalable backend systems and APIs for high-traffic applications.",
    responsibilities: [
      "Design and implement microservices architecture",
      "Build scalable APIs handling millions of requests",
      "Optimize database queries and system performance",
      "Implement caching strategies and load balancing",
      "Ensure security and data integrity",
    ],
    requirements: [
      "Expert Node.js, Python, or Go experience",
      "Database design and optimization skills",
      "Microservices and distributed systems knowledge",
      "AWS/GCP/Azure cloud services",
      "Strong problem-solving abilities",
    ],
  },
  {
    id: 6,
    title: "UI/UX Designer",
    company: "Cursor Inc.",
    location: "Remote",
    region: "global",
    type: "Full time",
    salary: "60k-180k",
    experience: "3-6 yrs exp",
    category: "Product Designer",
    postedDate: "4 hours ago",
    img: "/company-logo/cursor.svg",
    summary:
      "Design intuitive digital experiences, create user flows, and collaborate closely with product and engineering teams.",
    responsibilities: [
      "Conduct user research and usability testing",
      "Create wireframes, prototypes, and high-fidelity designs",
      "Build and maintain comprehensive design systems",
      "Collaborate with product and engineering teams",
      "Iterate on designs based on user feedback",
    ],
    requirements: [
      "Portfolio demonstrating UX/UI work",
      "Expert Figma proficiency",
      "User-centered design methodology",
      "Strong communication skills",
      "Understanding of accessibility standards",
    ],
  },
  {
    id: 7,
    title: "Graphic Designer Junior",
    company: "Logolab Global Pvt. Ltd.",
    location: "Kathmandu, Nepal",
    region: "nepal",
    type: "Full time",
    salary: "18k, 20K, 25K",
    experience: "0-3 yrs exp",
    category: "Graphic Design",
    postedDate: "5 hours ago",
    img: "/company-logo/logolab.png",
    summary:
      "Create compelling brand visuals, marketing assets, and campaign creatives with strong visual consistency.",
    responsibilities: [
      "Design social media graphics and marketing assets",
      "Collaborate with marketing and creative teams",
      "Maintain brand guidelines and consistency",
      "Prepare assets in multiple formats (Web, Print, Social)",
      "Assist in branding and rebranding projects",
    ],
    requirements: [
      "Proficiency in Adobe Suite (Photoshop, Illustrator, InDesign) or Figma",
      "Strong typography and layout skills",
      "Portfolio with branding/design work",
      "Ability to meet tight deadlines",
      "Attention to detail and color theory knowledge",
    ],
  },
  {
    id: 8,
    title: "Graphic Designer Senior",
    company: "Logolab Global Pvt. Ltd.",
    location: "Kathmandu, Nepal",
    region: "nepal",
    type: "Full time",
    salary: "70K, 80K, 90K",
    experience: "4-6 yrs exp",
    category: "Graphic Design",
    postedDate: "2 hours ago",
    img: "/company-logo/logolab.png",
    summary:
      "Lead design initiatives, develop comprehensive brand identities, and mentor junior designers.",
    responsibilities: [
      "Lead end-to-end brand identity development",
      "Create design systems and brand guidelines",
      "Mentor junior graphic designers",
      "Manage multiple design projects simultaneously",
      "Collaborate with clients on creative direction",
    ],
    requirements: [
      "4+ years of professional design experience",
      "Expert Adobe Suite and Figma knowledge",
      "Strong portfolio with branding projects",
      "Understanding of print and digital production",
      "Leadership and project management skills",
    ],
  },
  {
    id: 9,
    title: "Creative Designer",
    company: "Adspire Nepal Pvt. Ltd.",
    location: "Lazimpat, Kathmandu, Nepal",
    region: "nepal",
    type: "Full time",
    salary: "25k-40k",
    experience: "4-8 yrs exp",
    category: "Brand Development",
    postedDate: "6 hours ago",
    img: "/company-logo/cursor.svg",
    summary:
      "Develop comprehensive brand strategies, positioning, and messaging for growth-focused campaigns.",
    responsibilities: [
      "Conduct market research and competitive analysis",
      "Define brand positioning and value proposition",
      "Develop messaging frameworks and brand voice guidelines",
      "Create brand strategy presentations for clients",
      "Align marketing and business strategies",
    ],
    requirements: [
      "4+ years in brand strategy or marketing",
      "Strong analytical and research skills",
      "Excellent writing and storytelling abilities",
      "Experience with brand tools and frameworks",
      "Portfolio of strategic brand work",
    ],
  },
  {
    id: 10,
    title: "Social Media Manager",
    company: "Adspire Nepal Pvt. Ltd.",
    location: "Lazimpat, Kathmandu, Nepal",
    region: "nepal",
    type: "Full time",
    salary: "25k-40k",
    experience: "2-4 yrs exp",
    category: "Digital Marketing",
    postedDate: "3 hours ago",
    img: "/company-logo/cursor.svg",
    summary:
      "Plan content, manage social channels, and grow community engagement with data-driven strategies.",
    responsibilities: [
      "Develop monthly social content calendars",
      "Create and publish engaging content across platforms",
      "Analyze performance metrics and optimize strategies",
      "Manage community engagement and customer inquiries",
      "Collaborate with creative teams on campaigns",
    ],
    requirements: [
      "2+ years managing social media platforms",
      "Expert knowledge of analytics tools (Meta, Google Analytics)",
      "Strong copywriting and storytelling skills",
      "Familiarity with design tools for quick graphics",
      "Creative mindset and trend awareness",
    ],
  },
  {
    id: 11,
    title: "Digital Marketing Manager",
    company: "Growth Labs Australia",
    location: "Melbourne, Australia",
    region: "global",
    type: "Full time",
    salary: "85k-130k AUD",
    experience: "3-6 yrs exp",
    category: "Digital Marketing",
    postedDate: "7 hours ago",
    img: "/company-logo/cursor.svg",
    summary:
      "Lead integrated digital marketing campaigns, manage budgets, and drive measurable business growth.",
    responsibilities: [
      "Plan and execute multi-channel marketing campaigns",
      "Manage PPC, SEO, and content marketing strategies",
      "Analyze ROI and optimize campaign performance",
      "Manage marketing budgets and vendor relationships",
      "Lead cross-functional marketing team",
    ],
    requirements: [
      "3+ years digital marketing experience",
      "Expertise in Google Ads and Meta advertising",
      "Strong analytics and data interpretation skills",
      "SEO and SEM knowledge",
      "Project management and team leadership skills",
    ],
  },
  {
    id: 12,
    title: "Sales Development Representative",
    company: "SalesForce USA",
    location: "New York, USA",
    region: "global",
    type: "Full time",
    salary: "50k-80k + commission",
    experience: "1-3 yrs exp",
    category: "Sales",
    postedDate: "8 hours ago",
    img: "/company-logo/cursor.svg",
    summary:
      "Drive outbound sales, manage leads, and build pipeline for enterprise solutions.",
    responsibilities: [
      "Prospect and qualify leads through outreach",
      "Conduct discovery calls and product demos",
      "Handle objections and negotiate deals",
      "Maintain CRM data and sales pipeline",
      "Meet monthly sales targets and quotas",
    ],
    requirements: [
      "Strong communication and sales skills",
      "Comfortable working with sales targets",
      "CRM system proficiency (Salesforce/HubSpot)",
      "Self-motivated and resilient",
      "Bachelor's degree preferred",
    ],
  },
  {
    id: 13,
    title: "Account Manager",
    company: "ClientSuccess Dubai",
    location: "Dubai, UAE",
    region: "global",
    type: "Full time",
    salary: "65k-100k",
    experience: "2-5 yrs exp",
    category: "Account Management",
    postedDate: "9 hours ago",
    img: "/company-logo/cursor.svg",
    summary:
      "Manage client relationships, drive revenue growth, and ensure customer success across accounts.",
    responsibilities: [
      "Manage and grow assigned client accounts",
      "Handle contract renewals and upsell opportunities",
      "Prepare proposals and business reviews",
      "Track account performance and health metrics",
      "Serve as primary client point of contact",
    ],
    requirements: [
      "Strong communication and negotiation skills",
      "2+ years account management experience",
      "Ability to work with revenue targets",
      "Highly organized and detail-oriented",
      "CRM experience and sales acumen",
    ],
  },
  {
    id: 14,
    title: "Web Designer",
    company: "Growth Labs Australia",
    location: "Lazimpat, Kathmandu, Nepal",
    region: "global",
    type: "Full time",
    salary: "25k-40k",
    experience: "2-5 yrs exp",
    category: "Web Design",
    postedDate: "8 hours ago",
    img: "/company-logo/cursor.svg",
    summary:
      "Design modern web interfaces and landing pages with strong visual hierarchy and user experience.",
    responsibilities: [
      "Design responsive web layouts and prototypes",
      "Create UI kits and reusable component systems",
      "Collaborate with developers on implementation",
      "Ensure visual consistency with brand guidelines",
      "Conduct user testing and iterate designs",
    ],
    requirements: [
      "Strong portfolio with web design work",
      "Expert Figma and prototyping skills",
      "Deep understanding of responsive design",
      "Knowledge of web design trends and accessibility",
      "Attention to detail and visual design sense",
    ],
  },
];
